more cleanup and restructure

diff --git a/dmt-integrate b/dmt-integrate
--- a/dmt-integrate
+++ b/dmt-integrate
@@ -68,104 +68,82 @@ mkdir -p "$DMT_APPS_TARGET"
 
 INTEGRATE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-# echo
-# printf "app_base: ${YELLOW}${APP_BASE}${NC}\n"
-
 # sync
-if [ $APP_BASE = "" ]; then
+if [ $APP_BASE = your-app-base ]; then
 
   printf "${RED}Please open setting.json and change app_base to yours! "
   echo ''
   echo 'Not Successful'
-
-else
-    if [ "$SYNC_ONLY" != true ]; then
-      # before build
-      echo
-      printf "${GREEN}Changing app_base in svelte configuration:${NC}\n"
-      # setBase
-      node $INTEGRATE/editBase.js "$APP_ROOT_DIR"
-
-      # build
-      pnpm build
-
-      # after build
-
-      if [ $? -ne 0 ]; then # error
-        # resetBase
-        node $INTEGRATE/resetBase.js "$APP_ROOT_DIR"
-
-        echo
-        printf "${RED}Build error${NC}\n"
-        exit
-      fi
-
-      # resetBase
-      node $INTEGRATE/resetBase.js "$APP_ROOT_DIR"
-    fi
-
-    # sync frontend
-
-    if [ "$BUILD" != "undefined" ] && [ -d $SOURCE_PUBLIC ]; then
-      SOURCE_PUBLIC="${APP_ROOT_DIR}/${BUILD}"
-      mkdir -p "$DMT_APPS_TARGET/$APP_BASE"; cd $_
-
-      dirsync --exclude dmt --exclude dmt-install "$SOURCE_PUBLIC" .
-      # sometimes (rarely) build is "." and in these cases we need to exclude dmt and dmt-install
-    fi
-
-    # sync hook
-
-    ORIGIN_HOOK="${APP_ROOT_DIR}/${HOOK}"
-    INSTALLED_HOOK="$DMT_APPS_TARGET/${APP_BASE}/dmt"
-
-    if [ -d $ORIGIN_HOOK ]; then
-      mkdir -p "$INSTALLED_HOOK"; cd $_
-      dirsync "$ORIGIN_HOOK" .
-    elif [ -d "$INSTALLED_HOOK" ]; then # hook was deleted
-      rm -rf "$INSTALLED_HOOK"
-    fi
-
-    if [ "$SYNC_ONLY" != true ]; then
-
-      cd "$DMT_APPS_TARGET/$APP_BASE"
-
-      if [ -f "${APP_ROOT_DIR}/dmt-install/dmt-customize" ]; then
-        cp -r "${APP_ROOT_DIR}/dmt-install" .
-        printf "Detected ${YELLOW}dmt-customize${NC} script, executing ...\n"
-        ./dmt-install/dmt-customize
-        rm -rf dmt-install
-      fi
-
-      if [ -f "package.json" ]; then
-        pnpm install
-      fi
-
-      if [ -f "./index.js" ] || [ -f "./dmt/index.js" ]; then
-        dmt restart
-      fi
-
-    fi
-
-    cd "$APP_ROOT_DIR"
-
-    # node dmt-install/editAppHtml.cjs
-
-    # # build
-    # npm run build
-
-    # # after build scripts
-    # if [ -f dmt-install/editManifest.cjs ]; then node dmt-install/editManifest.cjs; fi
-    # node dmt-install/resetAppHtml.cjs
-    # node dmt-install/resetBase.cjs
-
-
-    # printf "${GREEN}✓ Updated ~/.dmt/apps${NC}\n"
-
-    # cd $SOURCE
-
-    # # if we wanted to sync the changes to server then uncomment below and change USERNAME & SERVER_IP
-    # echo 'rsync server'
-    # rsync -azP "$DMT_APPS/$app_base" "USERNAME@SERVER_IP:/home/USERNAME/.dmt/apps/user/$app_base"
+  exit
 
 fi
+
+if [ "$SYNC_ONLY" != true ]; then
+  # before build
+  echo
+  printf "${GREEN}Changing app_base in svelte configuration:${NC}\n"
+  # setBase
+  node $INTEGRATE/editBase.js "$APP_ROOT_DIR"
+
+  # build
+  pnpm build
+
+  # after build
+
+  if [ $? -ne 0 ]; then # error
+    # resetBase
+    node $INTEGRATE/resetBase.js "$APP_ROOT_DIR"
+
+    echo
+    printf "${RED}Build error${NC}\n"
+    exit
+  fi
+
+  # resetBase
+  node $INTEGRATE/resetBase.js "$APP_ROOT_DIR"
+fi
+
+# sync frontend
+
+if [ "$BUILD" != "undefined" ] && [ -d $SOURCE_PUBLIC ]; then
+  SOURCE_PUBLIC="${APP_ROOT_DIR}/${BUILD}"
+  mkdir -p "$DMT_APPS_TARGET/$APP_BASE"; cd $_
+
+  dirsync --exclude dmt --exclude dmt-install "$SOURCE_PUBLIC" .
+  # sometimes (rarely) build is "." and in these cases we need to exclude dmt and dmt-install
+fi
+
+# sync hook
+
+ORIGIN_HOOK="${APP_ROOT_DIR}/${HOOK}"
+INSTALLED_HOOK="$DMT_APPS_TARGET/${APP_BASE}/dmt"
+
+if [ -d $ORIGIN_HOOK ]; then
+  mkdir -p "$INSTALLED_HOOK"; cd $_
+  dirsync "$ORIGIN_HOOK" .
+elif [ -d "$INSTALLED_HOOK" ]; then # hook was deleted
+  rm -rf "$INSTALLED_HOOK"
+fi
+
+if [ "$SYNC_ONLY" != true ]; then
+
+  cd "$DMT_APPS_TARGET/$APP_BASE"
+
+  if [ -f "${APP_ROOT_DIR}/dmt-install/dmt-customize" ]; then
+    cp -r "${APP_ROOT_DIR}/dmt-install" .
+    printf "Detected ${YELLOW}dmt-customize${NC} script, executing ...\n"
+    ./dmt-install/dmt-customize
+    rm -rf dmt-install
+  fi
+
+  if [ -f "package.json" ]; then
+    pnpm install
+  fi
+
+  if [ -f "./index.js" ] || [ -f "./dmt/index.js" ]; then
+    dmt restart
+  fi
+
+fi
+
+cd "$APP_ROOT_DIR"
